In [102]:
import pandas as pd
import networkx as nx

In [79]:
read_data = pd.read_csv("pnas.1713568115.sd01.txt")
data = data[data['trial'] == 1]  #take the data for the 1st trial only
#print(len(data))

#data['begin'].dtype
data['time'] = data['end'] - data['begin']#store the diff btw begin and end to get total time for each trans. in ms
data['time'] = data['time']/1000.0 #change ms to s
data['time'] = data['time'].map(lambda x: [x])

In [80]:
read_data.head(10)

   trial  id1  id2         begin           end
0      1  201  219  1.373105e+12  1.373105e+12
1      1  201  219  1.373109e+12  1.373109e+12
2      1  201  242  1.373119e+12  1.373119e+12
3      1  201  242  1.373119e+12  1.373119e+12
4      1  201  255  1.372958e+12  1.372958e+12
5      1  201  259  1.372937e+12  1.372937e+12
6      1  201  259  1.373041e+12  1.373041e+12
7      1  201  259  1.373240e+12  1.373240e+12
8      1  201  262  1.373360e+12  1.373360e+12
9      1  201  263  1.373178e+12  1.373178e+12

In [81]:
id1_unique = data['id1'].unique()
id2_unique = data['id2'].unique()
len(id2_unique)

1159

In [82]:
df_new = data[:10]
print(df_new)

   trial  id1  id2         begin           end      time
0      1  201  219  1.373105e+12  1.373105e+12     [2.0]
1      1  201  219  1.373109e+12  1.373109e+12    [42.0]
2      1  201  242  1.373119e+12  1.373119e+12     [2.0]
3      1  201  242  1.373119e+12  1.373119e+12   [2.999]
4      1  201  255  1.372958e+12  1.372958e+12  [41.999]
5      1  201  259  1.372937e+12  1.372937e+12    [15.0]
6      1  201  259  1.373041e+12  1.373041e+12     [3.0]
7      1  201  259  1.373240e+12  1.373240e+12     [8.0]
8      1  201  262  1.373360e+12  1.373360e+12  [27.999]
9      1  201  263  1.373178e+12  1.373178e+12     [2.0]

In [99]:
data = data.groupby(['id1','id2']).agg({'time': 'sum'}) #group by id1 and id2 as nodes and time as a list of weights
data.head(100)

                                                      time
id1 id2
201 219                                        [2.0, 42.0]
    242                                       [2.0, 2.999]
    255                                           [41.999]
    259                                   [15.0, 3.0, 8.0]
    262                                           [27.999]
    263                                              [2.0]
    264                                              [3.0]
    267                                              [2.0]
    268                                         [5.0, 3.0]
    271                             [3.0, 13.0, 8.0, 13.0]
    272                                 [26.999, 2.0, 8.0]
    275                                        [12.0, 4.0]
    277                                              [3.0]
    279                                         [2.0, 2.0]
    280                                              [5.0]
    288                                           [10.999]
    289                                              [2.0]
    301                                         [2.0, 2.0]
    315                                   [18.0, 3.0, 2.0]
    332                                  [5.0, 7.999, 5.0]
    334                                             [19.0]
    335                                            [6.999]
    336                                         [2.0, 3.0]
    338                                              [2.0]
    340                                              [6.0]
    342                                       [4.0, 3.999]
    344                                              [2.0]
    347                                              [4.0]
    351                                              [2.0]
    355                                         [3.0, 5.0]
...                                                    ...
    495                                              [4.0]
    496                                              [4.0]
    498                                              [2.0]
    509                                              [4.0]
    511                                              [3.0]
    513                                         [7.0, 3.0]
    518                                              [2.0]
    520  [13.0, 2.0, 4.0, 2.0, 4.0, 4.0, 16.0, 10.0, 86...
    522                                              [6.0]
    549                                         [2.0, 2.0]
    555                                       [3.0, 9.999]
    556                              [3.0, 2.0, 4.0, 10.0]
    557                                    [7.0, 2.0, 2.0]
    564                                        [13.0, 2.0]
    567                                              [2.0]
    575                                              [2.0]
    576                                              [3.0]
    578                                             [10.0]
    594                                              [5.0]
    604                                              [4.0]
    608                                         [3.0, 3.0]
    613                                              [4.0]
    622                                              [3.0]
    623                                              [2.0]
    636                                              [2.0]
    637                                      [2.999, 26.0]
    639                             [42.0, 11.999, 18.999]
    640                                              [4.0]
    645                                              [3.0]
    647                                              [2.0]

[100 rows x 1 columns]

In [100]:
data = data.reset_index() #reset index after group by as there are some none values for column id1

In [101]:
data.head(100)

    id1  id2                                               time
0   201  219                                        [2.0, 42.0]
1   201  242                                       [2.0, 2.999]
2   201  255                                           [41.999]
3   201  259                                   [15.0, 3.0, 8.0]
4   201  262                                           [27.999]
5   201  263                                              [2.0]
6   201  264                                              [3.0]
7   201  267                                              [2.0]
8   201  268                                         [5.0, 3.0]
9   201  271                             [3.0, 13.0, 8.0, 13.0]
10  201  272                                 [26.999, 2.0, 8.0]
11  201  275                                        [12.0, 4.0]
12  201  277                                              [3.0]
13  201  279                                         [2.0, 2.0]
14  201  280                                              [5.0]
15  201  288                                           [10.999]
16  201  289                                              [2.0]
17  201  301                                         [2.0, 2.0]
18  201  315                                   [18.0, 3.0, 2.0]
19  201  332                                  [5.0, 7.999, 5.0]
20  201  334                                             [19.0]
21  201  335                                            [6.999]
22  201  336                                         [2.0, 3.0]
23  201  338                                              [2.0]
24  201  340                                              [6.0]
25  201  342                                       [4.0, 3.999]
26  201  344                                              [2.0]
27  201  347                                              [4.0]
28  201  351                                              [2.0]
29  201  355                                         [3.0, 5.0]
..  ...  ...                                                ...
70  201  495                                              [4.0]
71  201  496                                              [4.0]
72  201  498                                              [2.0]
73  201  509                                              [4.0]
74  201  511                                              [3.0]
75  201  513                                         [7.0, 3.0]
76  201  518                                              [2.0]
77  201  520  [13.0, 2.0, 4.0, 2.0, 4.0, 4.0, 16.0, 10.0, 86...
78  201  522                                              [6.0]
79  201  549                                         [2.0, 2.0]
80  201  555                                       [3.0, 9.999]
81  201  556                              [3.0, 2.0, 4.0, 10.0]
82  201  557                                    [7.0, 2.0, 2.0]
83  201  564                                        [13.0, 2.0]
84  201  567                                              [2.0]
85  201  575                                              [2.0]
86  201  576                                              [3.0]
87  201  578                                             [10.0]
88  201  594                                              [5.0]
89  201  604                                              [4.0]
90  201  608                                         [3.0, 3.0]
91  201  613                                              [4.0]
92  201  622                                              [3.0]
93  201  623                                              [2.0]
94  201  636                                              [2.0]
95  201  637                                      [2.999, 26.0]
96  201  639                             [42.0, 11.999, 18.999]
97  201  640                                              [4.0]
98  201  645                                              [3.0]
99  201  647                                              [2.0]

[100 rows x 3 columns]